### PR TITLE
Support For Hackernoon and Other Features

### PR DESCRIPTION
**Pull request by skeptrunedev**
Functionality Lost: 

- Ability to suffix an article with `summary` to get a summary

We felt like the UX around this was already poor and it wasn't a worthwhile feature to keep with a route that redirected and captured the information - that's the only strategy we think would work with multiple domains being supported - so we felt ok getting rid of it. 

In the future, it can be added back with an api route that redirects. 

Features: 

- [x] API Support for hackernoon through using playwright
- [x] URL Support for hackernoon
- [x] Changed from "TechCrunch" to "Article" for the name of the site since it's now more general-purpose
- [x] Added 'blink' animation and component which writes and then deletes all of the supported sites 
- [x] Added eslint and prettier configs
- [x] `Enter` triggers the request to get the summary 
- [x] `Paste` triggers the request to get the summary 
- [x] `scrollIntoView` as the summary populates
- [x] Toasts on all errors 

https://user-images.githubusercontent.com/15804464/217432868-9b86e02a-51bc-4ac4-aa64-841bd3d7b2c6.mp4

### CODE REVIEW

**Comment by Nutlope** [comment]
@kmkhami I really appreciate the detailed PR but I unfortunately can't accept this contribution because it changes too much about the site. I already have the Techcrunch specific domain and would like it to work for everyone who saw it on Twitter, for everyone who will see it in a bunch of AI newsletters going tomorrow, and for a video I'm working on that already incorporates the site as is.

I recommend you release your own version for Hackernoon or release this version on your own domain. Going to close for now but feel free to re-open or DM me on Twitter (@Nutlope) if you have any extra follow ups or comments.

**Comment by skeptrunedev** [comment]
> @kmkhami I really appreciate the detailed PR but I unfortunately can't accept this contribution because it changes too much about the site. I already have the Techcrunch specific domain and would like it to work for everyone who saw it on Twitter, for everyone who will see it in a bunch of AI newsletters going tomorrow, and for a video I'm working on that already incorporates the site as is.
> 
> I recommend you release your own version for Hackernoon or release this version on your own domain. Going to close for now but feel free to re-open or DM me on Twitter (@Nutlope) if you have any extra follow ups or comments.

Makes complete sense. No worries. Thanks for the great work! @

**Comment by Nutlope** [comment]
Your code is great @kmkhami, truly well done on it. There are also some interesting bits in there like scrolling into view,  triggering on `Enter`, and the added toasts for errors. Wanna submit a PR with just those three changes? Would love to incorporate them.

**Comment by skeptrunedev** [comment]
> Your code is great @kmkhami, truly well done on it. There are also some interesting bits in there like scrolling into view, triggering on `Enter`, and the added toasts for errors. Wanna submit a PR with just those three changes? Would love to incorporate them.

Yeah, give me about an hour. Vercel does not play nice with puppeteer or playwright and I'm trying to debug it. I got Medium and Investopedia working as well, but Vercel is making it real tough to get it to work :( . I'm 20 mins away from just going bare metal. 

I appreciate you allowing me to contribute those bits still! I'm also going to get the Redis cache going - maybe tomorrow - and will PR that as well if it's wanted :) .

**Comment by Nutlope** [comment]
> > Your code is great @kmkhami, truly well done on it. There are also some interesting bits in there like scrolling into view, triggering on `Enter`, and the added toasts for errors. Wanna submit a PR with just those three changes? Would love to incorporate them.
> 
> Yeah, give me about an hour. Vercel does not play nice with puppeteer or playwright and I'm trying to debug it. I got Medium and Investopedia working as well, but Vercel is making it real tough to get it to work :( . I'm 20 mins away from just going bare metal.
> 
> I appreciate you allowing me to contribute those bits still! I'm also going to get the Redis cache going - maybe tomorrow - and will PR that as well if it's wanted :) .

For sure, take your time! And wow, awesome that you have it working for both Medium and Investopedia. I'd love to know:

1. Why you're using puppeteer/playwright instead of sending a GET request to grab the site's HTML and parsing it
2. What specific issues you're facing with puppeteer on Vercel. Are you running into serverless timeouts?

**Comment by skeptrunedev** [comment]
Error w/ puppeteer: 
```
2023-02-08T05:43:36.555Z	1bc5452c-7af7-400f-9b31-b46561ff36b6	ERROR	Error: Could not find Chromium (rev. 1083080). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (file:///var/task/node_modules/puppeteer-core/lib/esm/puppeteer/node/ProductLauncher.js:101:27)
    at ChromeLauncher.executablePath (file:///var/task/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:176:25)
    at ChromeLauncher.launch (file:///var/task/node_modules/puppeteer-core/lib/esm/puppeteer/node/ChromeLauncher.js:64:37)
    at async handler (/var/task/.next/server/pages/api/playwright.js:29:21)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:253:36)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:384:29)
    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:322:20)
2023-02-08T05:43:36.556Z	1bc5452c-7af7-400f-9b31-b46561ff36b6	ERROR	Error: Could not find Chromium (rev. 1083080). This can occur 
```

Error w/ playwright [here](https://stackoverflow.com/questions/73325159/how-to-update-playwright-browsers-in-nextjs-vercel) . The fix mentioned in that post no longer works. Something in the black-box of the deploy is wiping out the chromium browsers. I am now trying [puppeteer-chromium-resolver](https://www.npmjs.com/package/puppeteer-chromium-resolver). 

For sites that require `js` - which are many because it serves as an anti-botting mechanism - you have to use something like playwright or puppeteer to spawn a browser process so you can scrape the site. 

ChatGPT can probably give an even better answer lol

**Pull request closed without merging**
